[project]
name = "stx-freelance-platform"
description = "Decentralized freelance platform on Stacks blockchain"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.escrow-multi-token-v7]
path = "contracts/escrow-multi-token-v7.clar"
clarity_version = 4
epoch = "latest"

[contracts.stxworks-escrow-v8]
path = "contracts/stxworks-escrow-v8.clar"
clarity_version = 4
epoch = "latest"

[contracts.verify-soulbound]
path = "contracts/verify-soulbound.clar"
clarity_version = 4
epoch = "latest"

[contracts.rep-sft]
path = "contracts/rep-sft.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
